spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travellife?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: admin
    password: 806175293
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
    level:
      root: warn
      com.travelsite.travellife: info
    file:
      name: log/travellife-pro.log

server:
  port: 8081




